name: List of Service principles 

on:
  push:
    branches:
      - main

      
jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Log in to Azure using environment variables
        run: |
          az login --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"
          
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"

      - name: List of service principles in subscription
        run: |
          echo "Script is starting"
          az ad sp list --all
          echo "Script is ending"
