name: Delete Azure Resources on main

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 15 * * *'  # 9 PM IST

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Log in to Azure using environment variables
        run: |
          az login --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"
          
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"

      - name: Delete All Resource Groups Immediately
        run: |
          echo "Starting deletion of all resource groups..."
          resource_groups=$(az group list --query "[].name" -o tsv)
          for rg in $resource_groups; do
            echo "Deleting resource group: $rg"
            az group delete --name "$rg" --yes --no-wait
          done
          echo "Deletion triggered for all resource groups."
